import { Command } from 'commander';
import { ConfigurationManager } from '@xec-sh/ops';
import { BaseCommand } from '../utils/command-base.js';
export declare class ConfigCommand extends BaseCommand {
    protected configManager: ConfigurationManager;
    constructor();
    create(): Command;
    execute(args: string[]): Promise<void>;
    private ensureInitialized;
    private setupSubcommands;
    private setupTargetCommands;
    private setupVarCommands;
    private setupTaskCommands;
    private setupDefaultsCommands;
    private interactiveMode;
    private viewConfig;
    private formatYamlWithDefaults;
    private getConfigValue;
    private setConfigValue;
    private unsetConfigValue;
    private listConfig;
    private manageTargets;
    private listTargets;
    private addTarget;
    private promptSSHConfig;
    private promptDockerConfig;
    private promptK8sConfig;
    private editTarget;
    private deleteTarget;
    private manageVars;
    private listVars;
    private setVar;
    private deleteVar;
    private importVars;
    private exportVars;
    private manageTasks;
    private listTasks;
    private viewTask;
    private createTask;
    private editTask;
    private deleteTask;
    private validateTasks;
    private manageDefaults;
    private manageCustomParameters;
    private readonly MANAGED_KEYS;
    private isCustomParameter;
    private listCustomParameters;
    private setCustomParameter;
    private getCustomParameter;
    private deleteCustomParameter;
    private exportCustomParameters;
    private viewDefaults;
    private setSSHDefaults;
    private setDockerDefaults;
    private setK8sDefaults;
    private setCommandDefaults;
    private resetDefaults;
    private runDoctor;
    private validateConfig;
    private saveConfig;
    private editTargetWithName;
    private deleteTargetWithName;
    private setVarWithKeyValue;
    private deleteVarWithKey;
    private importVarsFromFile;
    private exportVarsToFile;
    private viewTaskWithName;
    private deleteTaskWithName;
}
export default function command(program: Command): void;
