import { Command } from 'commander';
import { SubcommandBase } from '../utils/command-base.js';
export declare class DockerCommand extends SubcommandBase {
    constructor();
    protected getCommandConfigKey(): string;
    protected setupSubcommands(command: Command): void;
    private setupContainerCommands;
    private setupImageCommands;
    private setupServiceCommands;
    private setupComposeCommands;
    private setupNetworkCommands;
    private setupVolumeCommands;
    private setupSwarmCommands;
    private setupUtilityCommands;
    private setupQuickStart;
    private runContainer;
    private execInContainer;
    private stopContainers;
    private removeContainers;
    private viewContainerLogs;
    private buildImage;
    private pullImage;
    private removeImages;
    private listImages;
    private startRedisService;
    private startPostgresService;
    private startMysqlService;
    private startMongoDBService;
    private startRedisClusterService;
    private startKafkaService;
    private startRabbitMQService;
    private startElasticsearchService;
    private startSSHService;
    private listAvailableServices;
    private composeUp;
    private composeDown;
    private createNetwork;
    private removeNetwork;
    private createVolume;
    private removeVolume;
    private swarmInit;
    private swarmLeave;
    private listContainers;
    private pruneDocker;
    private quickStart;
    private getDockerDefaults;
    private getServiceDefaults;
}
export default function dockerCommand(program: Command): void;
