/**
 * Shell completion generator for bash, zsh, and fish.
 *
 * @example
 * ```typescript
 * import { generateCompletion } from '@xec-sh/ops/completion';
 *
 * // Generate shell completion script
 * const script = generateCompletion('bash', {
 *   binary: 'xec',
 *   commands: ['run', 'on', 'in', 'deploy', 'tasks', 'config'],
 *   flags: {
 *     global: ['--verbose', '--quiet', '--config', '--help'],
 *     run: ['--watch', '--eval', '--repl', '--typescript'],
 *     on: ['--target', '--parallel', '--timeout'],
 *   },
 *   dynamicCompletions: {
 *     '--target': 'xec targets --names-only',
 *     '--config': '_filedir yaml',
 *   },
 * });
 *
 * // Write to file
 * fs.writeFileSync('/etc/bash_completion.d/xec', script);
 * ```
 *
 * @module @xec-sh/ops/completion
 */

export type Shell = 'bash' | 'zsh' | 'fish';

export interface CompletionConfig {
  binary: string;
  commands: string[];
  flags?: Record<string, string[]>;
  dynamicCompletions?: Record<string, string>;
  descriptions?: Record<string, string>;
}

/**
 * Generate shell completion script
 */
export function generateCompletion(shell: Shell, config: CompletionConfig): string {
  switch (shell) {
    case 'bash':
      return generateBash(config);
    case 'zsh':
      return generateZsh(config);
    case 'fish':
      return generateFish(config);
  }
}

function generateBash(config: CompletionConfig): string {
  const { binary, commands, flags = {}, dynamicCompletions = {} } = config;
  const globalFlags = flags['global'] ?? [];

  return `# ${binary} bash completion
# Generated by @xec-sh/ops/completion

_${binary}_completions() {
  local cur prev words cword
  _init_completion || return

  local commands="${commands.join(' ')}"
  local global_flags="${globalFlags.join(' ')}"

  # Complete commands at position 1
  if [[ \${cword} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands} \${global_flags}" -- "\${cur}") )
    return
  fi

  # Complete flags per command
  local cmd="\${words[1]}"
  case "\${cmd}" in
${Object.entries(flags)
  .filter(([k]) => k !== 'global')
  .map(([cmd, cmdFlags]) => `    ${cmd})
      COMPREPLY=( $(compgen -W "${cmdFlags.join(' ')} \${global_flags}" -- "\${cur}") )
      ;;`)
  .join('\n')}
    *)
      COMPREPLY=( $(compgen -W "\${global_flags}" -- "\${cur}") )
      ;;
  esac

  # Dynamic completions for specific flags
${Object.entries(dynamicCompletions)
  .map(([flag, cmd]) => `  if [[ "\${prev}" == "${flag}" ]]; then
    COMPREPLY=( $(compgen -W "$(${cmd} 2>/dev/null)" -- "\${cur}") )
    return
  fi`)
  .join('\n')}
}

complete -F _${binary}_completions ${binary}
`;
}

function generateZsh(config: CompletionConfig): string {
  const { binary, commands, flags = {}, descriptions = {} } = config;
  const globalFlags = flags['global'] ?? [];

  return `#compdef ${binary}
# Generated by @xec-sh/ops/completion

_${binary}() {
  local -a commands
  commands=(
${commands.map((c) => `    '${c}:${descriptions[c] ?? c}'`).join('\n')}
  )

  local -a global_flags
  global_flags=(
${globalFlags.map((f) => `    '${f}[${descriptions[f] ?? f}]'`).join('\n')}
  )

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'command' commands
      _describe -t flags 'flags' global_flags
      ;;
    args)
      case $words[1] in
${Object.entries(flags)
  .filter(([k]) => k !== 'global')
  .map(([cmd, cmdFlags]) => `        ${cmd})
          _arguments ${cmdFlags.map((f) => `'${f}[${descriptions[f] ?? ''}]'`).join(' ')}
          ;;`)
  .join('\n')}
      esac
      ;;
  esac
}

_${binary}
`;
}

function generateFish(config: CompletionConfig): string {
  const { binary, commands, flags = {}, descriptions = {} } = config;
  const globalFlags = flags['global'] ?? [];

  const lines = [
    `# ${binary} fish completion`,
    `# Generated by @xec-sh/ops/completion`,
    '',
    `# Disable file completions by default`,
    `complete -c ${binary} -f`,
    '',
    `# Commands`,
    ...commands.map(
      (c) => `complete -c ${binary} -n '__fish_use_subcommand' -a '${c}' -d '${descriptions[c] ?? c}'`
    ),
    '',
    `# Global flags`,
    ...globalFlags.map(
      (f) => `complete -c ${binary} -l '${f.replace(/^--/, '')}' -d '${descriptions[f] ?? ''}'`
    ),
    '',
    `# Per-command flags`,
    ...Object.entries(flags)
      .filter(([k]) => k !== 'global')
      .flatMap(([cmd, cmdFlags]) =>
        cmdFlags.map(
          (f) =>
            `complete -c ${binary} -n '__fish_seen_subcommand_from ${cmd}' -l '${f.replace(/^--/, '')}' -d '${descriptions[f] ?? ''}'`
        )
      ),
  ];

  return lines.join('\n') + '\n';
}
