version: '1.0'
name: xec-sh
description: An Xec automation project
defaults:
  adapter: local
  shell: /bin/bash
  timeout: 30000
targets:
  local:
    type: local
  defaults:
    ssh:
      port: 22
      keepAlive: true
      keepAliveInterval: 30000
      timeout: 60000
    docker:
      workdir: /app
      tty: true
      interactive: true
    kubernetes:
      namespace: default
commands:
  exec:
    shell: /bin/sh
    tty: true
    interactive: true
  logs:
    tail: '50'
    timestamps: false
    follow: false
    prefix: false
    color: true
  cp:
    recursive: true
    preserveMode: true
    preserveTimestamps: false
    followSymlinks: false
  sync:
    delete: false
    exclude: []
    dryRun: false
  in:
    defaultTimeout: 30s
  'on':
    parallel: false
  copy:
    compress: true
    progress: true
  forward:
    dynamic: true
  watch:
    interval: 2
    clear: true
secrets:
  provider: env
vars: {}
tasks: {}
environments:
  development:
    env:
      NODE_ENV: development
      DEBUG: true
  production:
    env:
      NODE_ENV: production
      DEBUG: false
