[package]
name = "opentui"
version = "0.1.0"
edition = "2021"
authors = ["Aura-Next Contributors"]
description = "High-performance terminal rendering library"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]
name = "opentui"

[dependencies]
# Core dependencies
crossterm = "0.29.0"
once_cell = "1.21.3"
log = "0.4"

[features]
default = []

[profile.release]
opt-level = 3
lto = "fat"  # Better optimization than just 'true'
codegen-units = 1
strip = true
panic = "abort"  # Smaller binary, no unwinding
debug = false
overflow-checks = false  # Disable in release for performance

[profile.dev]
opt-level = 1  # Some optimization even in dev for better testing
debug = true
overflow-checks = true  # Keep checks in dev

# Cross-compilation targets
[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["wincon", "winbase", "consoleapi", "processenv"] }